name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Install Arm GNU Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install --yes gcc-arm-none-eabi

      - name: Build firmware
        run: make -j2
